### Loading the data of all sheets from Directionality Coding 2008-2016.xlsx

In [2]:
import pandas as pd
data1_2008 = pd.read_excel("Directionality Coding 2008-2016.xlsx", sheet_name="2008")
data1_2009 = pd.read_excel("Directionality Coding 2008-2016.xlsx", sheet_name="2009 RECODE")
data1_2010 = pd.read_excel("Directionality Coding 2008-2016.xlsx", sheet_name="2010")
data1_2011 = pd.read_excel("Directionality Coding 2008-2016.xlsx", sheet_name="2011")
data1_2012 = pd.read_excel("Directionality Coding 2008-2016.xlsx", sheet_name="2012")
data1_2013 = pd.read_excel("Directionality Coding 2008-2016.xlsx", sheet_name="2013")
data1_2014 = pd.read_excel("Directionality Coding 2008-2016.xlsx", sheet_name="2014")
data1_2015 = pd.read_excel("Directionality Coding 2008-2016.xlsx", sheet_name="2015")
data1_2016 = pd.read_excel("Directionality Coding 2008-2016.xlsx", sheet_name="2016")

## There are few records where year value is blank.Filling that value with year

In [3]:
data1_2010.Years.fillna(2012,inplace=True)
data1_2012.Years.fillna(2012,inplace=True)
data1_2013.Years.fillna(2013,inplace=True)
data1_2014.Years.fillna(2014,inplace=True)
data1_2015.Years.fillna(2015,inplace=True)

### Merging all the data from all dataframes(2008-2016)

In [4]:
frame=[data1_2008,data1_2009,data1_2010,data1_2011,data1_2012,data1_2013,data1_2014,data1_2015,data1_2016]
data=pd.concat(frame)

### Renaming the columns of data

In [5]:
data = data.rename(columns={'Origin Country': 'Origin_Country', 'Destination Country': 'Destination_Country',
                           '(Transit Country)':'Transit_Country','type of trafficking':'Type_Of_Trafficking',
                           'Victim Profile':'Victim_Profile'})

### Displaying the random rows of data

In [7]:
data.sample(5)

,Transit_Country,Destination_Country,Flagged,Means,Notes,Origin_Country,Sector,Unnamed: 11,Victim_Profile,Years,trafficker,Type_Of_Trafficking
1442,NaN,Mongolia,NaN,NaN,NaN,China,"1,10",NaN,NaN,2011.0,9,2
1187,NaN,Mongolia,NaN,NaN,NaN,North Korea,NaN,NaN,NaN,2009.0,4,2
2101,NaN,Namibia,NaN,NaN,NaN,Zimbabwe,NaN,NaN,3,2014.0,NaN,NaN
1412,NaN,Thailand,NaN,NaN,NaN,"Laos, People's Democratic Republic",NaN,NaN,4,2013.0,9,2
1543,NaN,Poland,NaN,NaN,NaN,Belarus,NaN,NaN,NaN,2010.0,11,1

## Getting Longitude and Latitude for Source and Destination countries

To Plot the directed graph lets first find out the logitude and latitude of each country and save it in new columns 

Getting Logitude and Latitude of Each Countries

Note: To use Geocoder.

> We need to signup in http://www.geonames.org/

> Use the username for connecting to geopy

> Need to enable the user acount

In [8]:
from geopy import geocoders
from geopy.geocoders import Nominatim
gn = geocoders.GeoNames(username='rose0037')
geolocator = Nominatim()

In [8]:
for country in data['Origin_Country'].unique():
    print(country)
    if (country == "Sub-Saharan Africa"):  ## pick the center one 
        location = geolocator.geocode("Africa")        
    else:
        if (country == "Former Soviet states" or country == "Former Soviet Union" ):
            location = geolocator.geocode("Soviet union")
        else:
            if (country != "Neighboring countries"):
                location = geolocator.geocode(country)
    data.loc[(data['Origin_Country']==country), 'Source_Latitude'] = location.latitude
    data.loc[(data['Origin_Country']==country), 'Source_Longitude'] = location.longitude

Afghanistan
China
Iran, Islamic Republic of
Tajikistan
Albania
Sub-Saharan Africa
Angola
Congo, Democratic Republic of
Argentina
Paraguay
Brazil
Dominican Republic
nan
Armenia
Ukraine
Russian Federation
Southeast Asia
Korea, Republic of
Taiwan, China
India
Philippines
Ireland
Africa
Bulgaria
Romania
Azerbaijan
Uzbekistan
Kyrgyz Republic
Kazakhstan
Moldova
Pakistan
Nepal
Sri Lanka
Bangladesh
Indonesia
Thailand
Ethiopia
Eritrea
Morocco
Eastern Europe
Central Asia
Myanmar
Belarus
Nigeria
Central America
Benin
Togo
Niger
Burkina Faso
Bolivia
Asia
Serbia
Bosnia and Herzegovina
Peru
Europe
United States
Cote d'Ivoire
Mali
Ghana
Burundi
Cambodia
Vietnam
Austria
Germany
Italy
United Kingdom
Singapore
Chad
Central African Republic
Congo
Cameroon
Latin America
Caribbean
Malaysia
Rwanda
Guinea
Chile
Neighboring countries
Mongolia
Korea, Democratic People's Republic of
Colombia
Uganda
Senegal
Nicaragua
Panama
Costa Rica
North Africa
Southeastern Europe
Canada
Cuba
Lebanon
Hungary
Greece
Georgia
Denmark
France
Spain
Haiti
Ecuador
Gulf States
Honduras
El Salvador
Gabon
Estonia
South America
Sierra Leone
Liberia
Guinea-Bissau
Gambia, The
Former Soviet states
West Africa
Guatemala
Guyana
Suriname
Venezuela
Australia
Egypt, Arab Republic of
Jordan
Turkey
Israel
East Africa
Middle East
Poland
Jamaica
Japan
East Asia
Kenya
Somalia
South Asia
Laos, People's Democratic Republic
Latvia
Syrian Arab Republic
Lithuania
Switzerland
Mauritius
Reunion
Malawi
Zambia
Mozambique
Tanzania
Western Europe
Mexico
Kosovo
Zimbabwe
Hong Kong
Norway
Turkmenistan
Northeast Asia
North America
Yemen, Republic of
Sudan
Macedonia, Former Yugoslav Republic of
Croatia
Slovenia
Slovak Republic
South Africa
Former Soviet Union
Iraq
Region
Timor-Leste
Tunisia
Uruguay
Lesotho
Swaziland
African countries

AttributeError: 'NoneType' object has no attribute 'latitude'

In [9]:
for country in data['Destination_Country'].unique():
    print(country)
    if (country == "Sub-Saharan Africa"):
        location = geolocator.geocode("Africa")
    else:
        if (country == "Former Soviet states" or country == "Former Soviet Union" ):
            location = geolocator.geocode("Soviet union")
        else:
            if (country != "Neighboring countries"):
                location = geolocator.geocode(country)
    data.loc[(data['Destination_Country']==country), 'Destination_Latitude'] = location.latitude
    data.loc[(data['Destination_Country']==country), 'Destination_Longitude'] = location.longitude

Pakistan
Iran, Islamic Republic of
Saudi Arabia
Oman
Gulf States
Afghanistan
Greece
Italy
Macedonia, Former Yugoslav Republic of
Kosovo
United Kingdom
France
Belgium
Norway
Germany
Netherlands
Europe
Algeria
Namibia
Angola
South Africa
Congo, Democratic Republic of
Portugal
Mexico
Western Europe
Argentina
Chile
Brazil
Spain
United Arab Emirates
Turkey
Russian Federation
Armenia
Australia
Austria
India
Bahrain
Malaysia
Jordan
Finland
Belize
Africa
Nigeria
Gabon
Cameroon
Togo
Cote d'Ivoire
Ghana
Congo
Guinea-Bissau
Benin
Peru
United States
nan
Bosnia and Herzegovina
Japan
South America
Caribbean
Middle East
West Africa
Mali
Niger
Burkina Faso
Thailand
China
Bangladesh
Korea, Republic of
Macau
Uganda
Vietnam
Taiwan, China
Cambodia
Switzerland
Canada
Central African Republic
Chad
Bolivia
Asia
Latin America
North America
East Asia
Congo, Republic of
Costa Rica
El Salvador
Guatemala
Cuba
The Bahamas, The
Cyprus
Czech Republic
Denmark
Southeast Asia
Djibouti
Panama
Haiti
Dominican Republic
Colombia
Venezuela
Ecuador
Israel
Egypt, Arab Republic of
Equatorial Guinea
Sweden
Lebanon
Kuwait
Sudan
Syrian Arab Republic
Yemen, Republic of
Qatar
Fiji
French Guiana
Gambia, The
Senegal
Guinea
Ukraine
Guyana
Neighboring countries
Barbados
Trinidad and Tobago
Suriname
Honduras
Hong Kong
Slovenia
Scandinavia
Nepal
Indonesia
Iraq
Singapore
Ireland
England
Jamaica
Bahamas, The
Philippines
Azerbaijan
Kenya
Tanzania
Guam
New Zealand
Pacific Islands
Kazakhstan
Latvia
Liberia
Libya
Luxembourg
Madagascar
Mozambique
Zambia
Malawi
Malta
Mauritania
Albania
Romania
Hungary
Slovak Republic
Mongolia
Nicaragua
North Africa
Papua New Guinea
Palau
Serbia
Sierra Leone
Region
Sri Lanka
Timor-Leste
Poland
Aruba
Botswana
Zimbabwe
Brunei
Solomon Islands
Somalia
Swaziland
Tunisia
Kyrgyz Republic
Iran
The Netherlands
Republic of Congo
Macedonia
UK
DRC
neighboring countries

AttributeError: 'NoneType' object has no attribute 'latitude'

### Removing unnamed columns from data

In [11]:

del data['Unnamed: 11']
data.head()

,Transit_Country,Destination_Country,Flagged,Means,Notes,Origin_Country,Sector,Victim_Profile,Years,trafficker,Type_Of_Trafficking,Source_Latitude,Source_Longitude,Destination_Latitude,Destination_Longitude
0,NaN,Pakistan,NaN,NaN,NaN,Afghanistan,NaN,NaN,2008.0,11,1,33.768006,66.238514,30.330840,71.247499
1,NaN,"Iran, Islamic Republic of",NaN,NaN,NaN,Afghanistan,NaN,NaN,2008.0,11,1,33.768006,66.238514,32.940750,52.947134
2,NaN,Saudi Arabia,NaN,NaN,NaN,Afghanistan,NaN,NaN,2008.0,11,1,33.768006,66.238514,13.968817,121.525087
3,NaN,Oman,NaN,NaN,NaN,Afghanistan,NaN,NaN,2008.0,11,1,33.768006,66.238514,25.227893,55.176669
4,NaN,Gulf States,X,NaN,NaN,Afghanistan,NaN,NaN,2008.0,NaN,NaN,33.768006,66.238514,42.710048,-71.441458

### Saving this data to excel sheet named Human_Traffic_data.csv

In [17]:
data.to_csv("Human_Traffic_data.csv",sep=',')

### Loading the data from Human_Traffic_data.csv file

In [18]:
data=pd.read_csv('Human_Traffic_data.csv', encoding= 'ISO-8859-1')

In [19]:
data.head()

,Unnamed: 0,Transit_Country,Destination_Country,Flagged,Means,Notes,Origin_Country,Sector,Victim_Profile,Years,trafficker,Type_Of_Trafficking,Source_Latitude,Source_Longitude,Destination_Latitude,Destination_Longitude
0,0,NaN,Pakistan,NaN,NaN,NaN,Afghanistan,NaN,NaN,2008,11,1,33.768006,66.238514,30.330840,71.247499
1,1,NaN,"Iran, Islamic Republic of",NaN,NaN,NaN,Afghanistan,NaN,NaN,2008,11,1,33.768006,66.238514,32.940750,52.947134
2,2,NaN,Saudi Arabia,NaN,NaN,NaN,Afghanistan,NaN,NaN,2008,11,1,33.768006,66.238514,13.968817,121.525087
3,3,NaN,Oman,NaN,NaN,NaN,Afghanistan,NaN,NaN,2008,11,1,33.768006,66.238514,25.227893,55.176669
4,4,NaN,Gulf States,X,NaN,NaN,Afghanistan,NaN,NaN,2008,NaN,NaN,33.768006,66.238514,42.710048,-71.441458